alias taa='terraform apply -auto-approve'
alias taad='terraform apply -auto-approve -destroy'
alias tar='terraform apply -replace='
alias tc='terraform console'
alias tfr='terraform fmt -recursive'
alias ti='terraform init'
alias tp='terraform plan'
alias tr='terraform refresh'