version: "3.9"

services:
  web:
    build: .
    image: my_web_sample
    container_name: my_web_sample-web
    environment:
      DB_HOST: 192.168.83.3
      DB_PORT: 5432
      DB_NAME: my_web_sample
      DB_USERNAME: my_web_sample
      DB_PASSWORD: my_web_sample
      DB_PASSEMAIL_SERVER_USER: ""
      EMAIL_SERVER_PASSWORD: ""
      EMAIL_SERVER_HOST: smtp
      EMAIL_SERVER_PORT: 1025
      EMAIL_FROM=no-reply@test.comWORD: my_web_sample
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      app_net:
        ipv4_address: 192.168.83.1
    volumes:
      - ../project:/home/developer/project
      - ~/.aws/keiju:/home/developer/.aws
      - .bash_profile:/home/developer/.bash_profile
      - .bashrc:/home/developer/.bashrc
      - .bash_aliases:/home/developer/.bash_aliases
      - .bash_functions:/home/developer/.bash_functions
      - .vimrc:/home/developer/.vimrc
    tty: true
  localstack:
    container_name: "my_web_sample-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      app_net:
        ipv4_address: 192.168.83.2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-../localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # db:
  #   image: postgres:16.3-alpine3.20
  #   container_name: my_web_sample_postgres
  #   environment:
  #     POSTGRES_USER: my_web_sample
  #     POSTGRES_DB: my_web_sample
  #     POSTGRES_PASSWORD: my_web_sample
  #     PGDATE: /var/lib/postgresql/data
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
  #     TZ: Asia/Tokyo
  #   command: postgres -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=2
  #   ports:
  #     - "127.0.0.1: 5432:5432"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.200.8.3
  #   volumes:
  #     - ../postgresql_data:/var/lib/postgresql/data
  # smtp:
  #   image: schickling/mailcatcher
  #   ports:
  #     - "127.0.0.1:1080:1080"
  #     - "127.0.0.1:1025:1025"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.200.81.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.83.0/24

volumes:
  posgre_data: null
