version: "3.7"
services:
  app:
    image: fluent/fluent-bit:latest
    # command: ["-v", "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"]
    # command: ["-p", "24224:24224",]
    # command: ["-i", "mem", "-o", "stdout", "-f", "1"]
    # ports:
    #   - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
    tty: true