version: "3.9"

services:
  web:
    build:
      context:
      dockerfile:
    image:
    container_name:
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address:
    volumes:
      - ../app:
    tty:
  db:
    image:
    container_name:
    environment:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
      PGDATE:
      POSTGRES_INITDB_ARGS:
      TZ:
    command:
      tcp_keepalives_count=2
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address:
    volumes:
      - posgre_data:

networks:
  app_net:
    driver:
    ipam:
      driver:
      config:
        - subnet:

volumes:
  posgre_data:
