version: "3.9"

services:
  web:
    build: .
    container_name: nursing-care-taxi-reservation
    ports:
      - "127.0.0.1:10000:3000"
    networks:
      app_net:
        ipv4_address: 192.24.7.27
    volumes:
      - ../app:/home/need/app
    tty: true
    privileged: true
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:14566:4566" # LocalStack Gateway
      - "127.0.0.1:14510-14559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      app_net:
        ipv4_address: 192.24.7.26
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-../localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  smtp:
    image: schickling/mailcatcher
    ports:
      - "127.0.0.1:10800:1080"
      - "127.0.0.1:10250:1025"
    networks:
      app_net:
        ipv4_address: 192.24.7.28
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.24.7.25/24
