version: "3.9"

services:
  web:
    build: .
    container_name: demo_projects
    networks:
      app_net:
        ipv4_address: 192.168.10.4
    volumes:
      - ../project:/home/developer/project
      - ~/.aws/keiju:/home/developer/.aws
      - .bash_profile:/home/developer/.bash_profile
      - .bashrc:/home/developer/.bashrc
      - .bash_aliases:/home/developer/.bash_aliases
      - .bash_functions:/home/developer/.bash_functions
      - .vimrc:/home/developer/.vimrc
    tty: true
    privileged: true
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
