version: "3.9"

services:
  terraform:
    build: .
    container_name: ${CONTAINER_NAME?err}
    ports:
      - "1111:1111"
    networks:
      app_net:
        ipv4_address: 192.1.10.6
    volumes:
      - ../app:/home/terraform/app
    tty: true
    privileged: true
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.1.10.5/24
