version: "3.9"

services:
  web:
    build: .
    container_name: demo_projects
    ports:
      - "11111:11111"
    networks:
      app_net:
        ipv4_address: 192.1.10.1
    volumes:
      - ../project:/home/developer/project
    tty: true
    privileged: true
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.1.10.0/24
