version: "3.9"

services:
  maruti:
    build: .
    container_name: tauri
    networks:
      app_net:
        ipv4_address: 10.24.81.10
    volumes:
      - ../project:/home/developer/project
      - /opt/android_sdk:/home/developer/project/android_sdk
    tty: true
    privileged: true
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.24.81.0/24
