version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: app.dockerfile
    image: template
    container_name: template
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 192.168.229.26
    volumes:
      - ../app:/home/template/app
    tty: true
  db:
    image: postgres:14.5-alpine3.16
    container_name: template_postgres
    environment:
      POSTGRES_USER: template
      POSTGRES_DB: template
      POSTGRES_PASSWORD: template
      PGDATE: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: Asia/Tokyo
    command: postgres -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=2
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.229.27
    volumes:
      - ../db:/var/lib/postgresql/data
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      app_net:
        ipv4_address: 192.168.229.28

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.229.25/24
