version: "3.9"

services:
  web:
    build:
      context: .
    image: my_web_sample
    container_name: my_web_sample
    environment:
      DISPLAY: :0
      DB_HOST: 192.168.229.27
      DB_PORT: 5432
      DB_NAME: my_web_sample
      DB_USERNAME: my_web_sample
      DB_PASSWORD: my_web_sample
      DB_PASSEMAIL_SERVER_USER: ""
      EMAIL_SERVER_PASSWORD: ""
      EMAIL_SERVER_HOST: smtp
      EMAIL_SERVER_PORT: 1025
      EMAIL_FROM=no-reply@test.comWORD: my_web_sample
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 192.168.229.26
    volumes:
      - ../app:/home/my_web_sample/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
  # db:
  #   image: postgres:14.5-alpine3.16
  #   container_name: my_web_sample_postgres
  #   environment:
  #     POSTGRES_USER: my_web_sample
  #     POSTGRES_DB: my_web_sample
  #     POSTGRES_PASSWORD: my_web_sample
  #     PGDATE: /var/lib/postgresql/data
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
  #     TZ: Asia/Tokyo
  #   command: postgres -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=2
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.168.229.27
  #   volumes:
  #     - ../postgresql_data:/var/lib/postgresql/data
  # smtp:
  #   image: schickling/mailcatcher
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.168.229.28

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.229.25/24

volumes:
  posgre_data: null
