version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: node.dockerfile
    image: mysite
    container_name: mysite
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    volumes:
      - ../app:/home/mysite/app
    tty: true
  db:
    image: postgres:14.0-alpine3.14
    container_name: postgres
    environment:
      POSTGRES_USER: ksj
      POSTGRES_DB: mysite
      POSTGRES_PASSWORD: myroad710
      PGDATE: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: Asia/Tokyo
    command: postgres -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c
      tcp_keepalives_count=2
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    volumes:
      - posgre_data:/var/lib/postgresql/data

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

volumes:
  posgre_data: null
