version: "3.9"

services:
  web:
    build: .
    container_name: giving_spirit
    networks:
      app_net:
        ipv4_address: 192.25.1.28
    volumes:
      - ../project:/home/developer/project
      - ~/.aws/nursing-care-taxi-reservation:/home/developer/.aws
      - .bash_profile:/home/developer/.bash_profile
      - .bashrc:/home/developer/.bashrc
      - .bash_aliases:/home/developer/.bash_aliases
      - .bash_functions:/home/developer/.bash_functions
      - .vimrc:/home/developer/.vimrc
    tty: true
    privileged: true
  db:
    image: mysql:9.2.0
    container_name: giving_spirit_mysql_9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_bin
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ../db:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 192.25.1.27
  localstack:
    container_name: "giving_spirit_reservation_localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      app_net:
        ipv4_address: 192.25.1.26
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-../localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  smtp:
    image: schickling/mailcatcher
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:1025:1025"
    networks:
      app_net:
        ipv4_address: 192.25.1.25
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.25.1.0/24
