version: "3.9"

services:
  web:
    build: .
    container_name: ${APP_NAME?err}
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 192.23.9.19
    volumes:
      - ../app:/home/${APP_NAME?err}/app
    tty: true
  db:
    image: postgres:14.5-alpine3.16
    container_name: ${APP_NAME?err}_postgres
    env_file:
      - db.env
    command: postgres -c tcp_keepalives_idle=30 -c tcp_keepalives_interval=10 -c tcp_keepalives_count=2
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.23.9.18
    volumes:
      - ../db:/var/lib/postgresql/data
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      app_net:
        ipv4_address: 192.23.9.17

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.23.9.16/24
