version: "3.9"

services:
  terraform:
    build: .
    container_name: ${APP_NAME?err}
    ports:
      - "2222:2222"
    networks:
      app_net:
        ipv4_address: 192.23.10.6
    volumes:
      - ../app:/home/${APP_NAME?err}/app
    tty: true
    privileged: true
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.23.10.5/24
